In [1]:
import numpy as np

In [3]:
# np arr
arr  = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#dtype,ndim,shape,reshape,size
print(arr.size, arr.shape,arr.ndim,arr.dtype)

9 (3, 3) 2 int32


In [9]:
#np arrange
arr1 = np.arange(40)
arr2 = np.arange(1,100,5)
print(arr1,arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39] [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [16]:
"""linspace it is same as arange"""
arr3 = np.linspace(1,100, 6)
arr3

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [14]:
# np zeros and ones
arrz = np.zeros(10, dtype = np.float32)
arro = np.ones(11, dtype= np.float16)
arro1 = np.ones((4,4), dtype=np.float64)
print(arrz, ">>>", arro, ">>>", arro1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] >>> [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] >>> [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# diogonal identy matrx 0 to 1
arre = np.eye(5)
arre

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# full array
arrf = np.full((4,4),10)
arrf

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [20]:
# random array
arrr = np.random.rand(5,5) #5*5 matrx float 0 to 1
arrr1 = np.random.rand(5,5)*100 # 0 to 100
arrri = np.random.randint(10,size=(5,5))
print(arrr ,">>>>>>>>>" ,arrr1,">>>>>>>>>>>>>>>>",arrri)

[[5.94774968e-01 7.60336248e-01 2.13475683e-01 4.98787604e-01
  6.51936045e-01]
 [8.50446465e-01 1.33244367e-01 2.48184473e-04 5.40605497e-01
  3.42114646e-02]
 [7.46831256e-01 5.58788300e-03 9.52662826e-01 3.00322907e-01
  9.95701879e-01]
 [5.84700729e-01 4.92242104e-01 5.63169667e-01 6.86287736e-01
  5.45041175e-01]
 [6.07187123e-01 1.94429950e-02 9.99233612e-01 7.06026743e-02
  9.22631715e-01]] >>>>>>>>> [[71.91117759 47.11745622  3.93340933 23.26803254 63.37516169]
 [33.62510286 20.58549964 48.74299369 51.15573062 75.80402085]
 [78.94016097 53.23629055 22.31263697 71.18638296 37.80293833]
 [75.80981791 66.37151562  1.02775339 68.96584099 32.66898761]
 [80.90952948 36.2901519  69.70607757 81.86376813 41.68174184]] >>>>>>>>>>>>>>>> [[1 0 5 8 1]
 [8 7 6 9 2]
 [1 8 4 6 7]
 [5 3 0 6 5]
 [2 4 2 9 3]]


In [24]:
# inspecting properties
print(arr.size,
      arr.shape,
      arr.dtype,
      arr.tolist(),
      np.info(np.eye))
arr.astype(dtype = np.float32)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [36]:
#copying ,sorting , reshapingabs
ar1 = np.copy(arr)
ar2 = arr.sort()
ar3 = np.random.rand(2,2) #for flatten
ar4 = ar3.flatten()
ar5 = ar3.T # transpose
ar6 = np.arange(1, 10) # for reshape
ar7 = ar6.reshape(3,3)
# ar8 = ar6.resize(5,5)
print(ar1, ">>>>", ar2,">>>>>>>", ar3,">>>>>>>>", ar4,">>>>>>>>", ar5,">>>>", ar6,">>>>>>", ar7)


[[1 2 3]
 [4 5 6]
 [7 8 9]] >>>> None >>>>>>> [[0.08915544 0.84906874]
 [0.61715791 0.78195949]] >>>>>>>> [0.08915544 0.84906874 0.61715791 0.78195949] >>>>>>>> [[0.08915544 0.61715791]
 [0.84906874 0.78195949]] >>>> [1 2 3 4 5 6 7 8 9] >>>>>> [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# adding/ removing elements

arra = np.arange(1,10) # for append
arrap = np.append(arra, 12)
arrin = np.insert(arra, 5, 55)
print(arrap, ">>>>>>>", arrin)

arrnew = np.array([[1,2,3],[4,5,6], [7,8,9]])
#arrd = np.delete(arrnew, 3, axis=0)
#arrdc = np.delete(arrnew, 3, axis=1)

[ 1  2  3  4  5  6  7  8  9 12] >>>>>>> [ 1  2  3  4  5 55  6  7  8  9]


In [46]:
# combining \ splitting

arr10 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr11 = np.array([[10,20,30],[40,50,60], [70,80,90]])
arrcr = np.concatenate((arr10, arr11), axis=0)
arrcc = np.concatenate((arr10, arr11), axis=1)
print(arrcr)
print(arrcc)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]


In [63]:
# indexing \ slicing\ subsetting

arrayy = np.arange(6)
print(arrayy[5])
print(arrayy[0:5])
#print(arrayy[2]=3)

arrayy1 = np.random.randint(12, size=(5,5))
print(arrayy1[0:3,4])
print(arrayy[:3])
#print(arrayy[:,1])
#arrayy1<5 # Returns an array with boolean values
#(arrayy1<3) & (arr2>5) # Returns an array with boolean values
#~arrayy1 # Inverts a boolean array
#arrayy1[arrayy1<5] # Returns array elements smaller than 5

5
[0 1 2 3 4]
[ 8  3 11]
[0 1 2]


In [73]:
# scalar math
arrs = np.arange(0,10)
arrs1 = np.arange(0,10)
print(arrs,">>>>>>", arrs1)

a_11 = np.add(arrs,1)
a_12 = np.subtract(arrs,1)
a_13 = np.multiply(arrs,2)
a_14 = np.divide(arrs,3)
a_15 = np.power(arrs,5)


#vector math 
print(
a_1 = np.add(arrs, arrs1),
a_2 = np.subtract(arrs, arrs1),
a_3 = np.multiply(arrs, arrs1), # Elementwise multiply arr1 by arr2
a_4 = np.divide(arrs, arrs1), # Elementwise divide arr1 by arr2
)   
print(
a_5 = np.power(arrs, arrs1), # Elementwise raise arr1 raised to the power of arr2
a_6 = np.array_equal(arrs, arrs1), # Returns True if the arrays have the same elements and shape
a_7 = np.sqrt(arrs) ,# Square root of each element in the array
a_8 = np.sin(arrs), # Sine of each element in the array
    
)
print(
a_9 = np.log(arrs), # Natural log of each element in the array
a_10 = np.abs(arrs) ,# Absolute value of each element in the array
a_11 = np.ceil(arrs), # Rounds up to the nearest int
a_12 = np.floor(arrs), # Rounds down to the nearest int
)
print(
a_13 = np.round(arrs) ,# Rounds to the nearest int
)

[0 1 2 3 4 5 6 7 8 9] >>>>>> [0 1 2 3 4 5 6 7 8 9]


C:\Users\USER\Anaconda3\envs\intuitive-deep-learning\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


TypeError: 'a_1' is an invalid keyword argument for print()

In [77]:
#statistics

arrlast = np.arange(1,22)
print(arrlast)

stm = np.mean(arrlast)
sts = np.sum(arrlast)
stv = np.var(arrlast)
stsd = np.std(arrlast)
#stco = arrlast.corrcoef()
stmi = np.min(arrlast)
stma = np.max(arrlast)
print(stm , sts, stv, stsd)

print(stmi, stma)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
11.0 231 36.666666666666664 6.0553007081949835
1 21


In [ ]:
""" ENDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"""